name: LifeSim
description: incredibly shitty, inspired by the Game of Life from Problem Sleuth
version: 2.8.1
homepage: https://github.com/FarragoFiction/LifeSim
author: jadedResearcher

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  RenderingLib:
    git: git://github.com/FarragoFiction/RenderingLib.git
  DollLibCorrect:
    git:  git://github.com/FarragoFiction/DollLibCorrect.git
  BlackJack:
    git:  git://github.com/FarragoFiction/BlackJack.git
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git
  TextEngine:
    git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  build_config: any